openapi: 3.2.0
info:
  title: Endpoints Data API
  description: "Our API provides the necessary services to access data programmatically. You first need to utilize the **Data-Assets endpoint** to obtain the **dataset ID** before you can call the Details, Data, and Dictionary endpoints. The dataset ID is required to retrieve the respective dataset information.\n\n Please note that executing the endpoints directly on this page will only return the first 100 rows, whereas you can expect the full dataset when executing them from the browser or your application. You can get a  [better understanding of our APIs](/developer/gettingstarted/understanding-our-apis/) by reviewing our documentaiton."
  x-logo:
    url: /public/logo512.png
host: https://api-staging.data.ferc.gov/v1
schemes:
- https
security:
- ApiKeyQueryAuth: []
tags:
- name: Data
paths:
  /dataset/{id}/data/:
    get:
      tags:
      - Data
      summary: Fetch the actual dataset rows
      description: This endpoint returns all the data for the ID you provide. First, use Data-Assets endpoint to find a valid dataset ID.
      parameters:
      - name: id
        in: path
        description: Enter the dataset ID number you want to retrieve
        required: true
        schema:
          type: string
          example: 1
      operationId: data-id
      responses:
        '200':
          description: Successfully returned list of datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  example:
                    row_data:
                    - '...': '...'
        '400':
          description: Bad Request - Invalid query parameters
        '401':
          description: Unauthorized - Request unsuccessful due to lack of validation
        '404':
          description: Not Found - Dataset ID does not exist
        '405':
          description: Method Not Allowed - Only GET requests are allowed
        '429':
          description: Too Many Requests - Blocked due to multiple requests in a short period
        '500':
          description: Internal Server Error - Database error or server failure
components:
  securitySchemes:
    ApiKeyQueryAuth:
      type: apiKey
      in: query
      name: api_key
